﻿namespace BookStoreApp.Blazor.Server.UI.Services.Base
{
    /// <summary>
    /// Extends to HttpClient generated by the swagger return the http client object
    /// </summary>
    public partial class Client : IClient
    {
        public HttpClient HttpClient
        {
            get
            {
                return _httpClient;
            }
        }
    }
}